// export const employeeAssetData  = [
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Manual',
//     assetNo: '124785',
//     collectionDate: '06 Apr 2025',
//   },
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Biometric',
//     assetNo: '124785',
//     collectionDate: '07 Apr 2025',
//   },
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Manual',
//     assetNo: '124785',
//     collectionDate: '08 Apr 2025',
//   },
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Biometric',
//     assetNo: '124785',
//     collectionDate: '09 Apr 2025',
//   },
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Manual',
//     assetNo: '124785',
//     collectionDate: '10 Apr 2025',
//   },
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Biometric',
//     assetNo: '124785',
//     collectionDate: '11 Apr 2025',
//   },
//   {
//     name: 'John Doe',
//     employeeId: '123456',
//     department: 'IT',
//     assetType: 'Manual',
//     assetNo: '124785',
//     collectionDate: '12 Apr 2025',
//   },
// ];
